# fully automated
amex:
  name: "Liabilities:US:AmEx:Green"
  currency: USD
  importer: OFX
  downloader: OFX
  OFX-id: 424 # https://www.ofxhome.com/index.php/institution/view/424
  op-id: "<1Password UUID>"
  account-id: "1234567"

# totally manual
bofa:
  name: "Assets:US:BofA:Checking"
  currency: USD
  importer: CSV
  downloader: custom
  instructions:
    Go to the site and fownload in CSV format from the account page
  filename_regexp: "BankOfAmerica\\.csv"
  column_map: # keys from beancount.ingest.importers.csv.Col
    DATE: "Date"
    AMOUNT_DEBIT: "Debit"
    AMOUNT_CREDIT: "Credit"
    PAYEE: "Description"
    BALANCE: "Balance"

# import is OFX (less error-prone than CSV), but downloading is manual
chase:
  name: "Assets:US:Chase:Checking"
  currency: USD
  importer: OFX
  downloader: custom
  instructions:
    Go to the site and download in OFX format from the account page
  account-id: "87654321"
