importers:
  plaid-bank:
    downloader: plaid
    op-id: "5ncfmu6iaffivid3ffniptuxvq" # Plaid 1P item
    accounts:
      - name: "Assets:US:Plaid:Checking"
        id: "N54ZAQKLNJSg48WvPnnKTeQPkxnRVasWGkmQ1" # Plaid account ID
        currency: USD
        number: "0000"
      - name: "Liabilities:US:Plaid:CreditCard"
        id: "Z5ondK7kMaSJox45AEE1i3y8dAPGw5igE9VGL"
        currency: USD
        number: "3333"
    importer: none
